/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
*/

package FindTheDifference;

import javax.sound.sampled.SourceDataLine;

public class Solution {
    public static void main(String[] args) {
        
        String s = "abcd";
        String t = "abcde";
        int[] freq = new int[26];
        for(char ch : s.toCharArray()) {
            freq[ch - 'a']++;
        }
        for(char ch : t.toCharArray()) {
            freq[ch - 'a']--;
            if(freq[ch - 'a'] < 0) System.out.println(ch);
        }
        // return ' ';
        System.out.println(" ");
    }
}

